OUTPUT_DIR: exp_AVT+ConvBiLSTM+PHQ-Subscores+Sub-Attention+Soft
SAVE_CONFIG_NAME: config_AVT+ConvBiLSTM+PHQ-Subscores+Sub-Attention+Soft.yaml
CKPTS_DIR: /home/zjy/workspace/DepressionRec/dataset/ckpts_fusion/
TYPE: AVT+ConvBiLSTM+PHQ-Subscores+Sub-Attention+Soft
MANUAL_SEED: 1
LOG_TITLE: Depression Detection with audio + visual + text data, ConvBiLSTM, PHQ-Subscores,
  Fusion-Sub-Attention, KLDivLoss(soft-label), ASAM
DATA:
  TRAIN_ROOT_DIR: 
    /home/zjy/workspace/DepressionRec/dataset/DAIC_WOZ-generated_database_V2/train/clipped_data/
  VALIDATION_ROOT_DIR: 
    /home/zjy/workspace/DepressionRec/dataset/DAIC_WOZ-generated_database_V2/train/original_data/
  TEST_ROOT_DIR: 
    /home/zjy/workspace/DepressionRec/dataset/DAIC_WOZ-generated_database_V2/test/clipped_data/
  USE_MEL_SPECTROGRAM: true
  VISUAL_WITH_GAZE: true
  PADDING:
  RESCALE_SIZE:
  CROP_SIZE:
  BATCH_SIZE: 240
  NUM_WORKERS: 0
MODEL:
  PHQ_THRESHOLD: 10
  EPOCHS: 100
  WEIGHTS:
    TYPE: absolute_path
    DATE:
    PATH: model_weights
    NAME:
    CUSTOM_ABSOLUTE_PATH: 
      /home/zjy/workspace/DepressionRec/alg/DepressionEstimation/models/AVT_ConvLSTM_Sub_Attention/model_weights/AVT+ConvBiLSTM+PHQ-Subscores+Sub-Attention.pt
    INCLUDED:
    - audio_net
    - visual_net
    - text_net
    - evaluator
  VISUAL_NET:
    INPUT_DIM: 3
    CONV_HIDDEN: 256
    LSTM_HIDDEN: 256
    OUTPUT_DIM: 256
    NUM_LAYERS: 4
    ACTIVATION: relu
    NORM: bn
    DROPOUT: 0.7
  AUDIO_NET:
    INPUT_DIM: 80
    CONV_HIDDEN: 256
    LSTM_HIDDEN: 256
    OUTPUT_DIM: 256
    NUM_LAYERS: 4
    ACTIVATION: relu
    NORM: bn
    DROPOUT: 0.7
  TEXT_NET:
    INPUT_DIM: 512
    CONV_HIDDEN: 256
    LSTM_HIDDEN: 256
    OUTPUT_DIM: 256
    NUM_LAYERS: 2
    ACTIVATION: relu
    NORM: bn
    DROPOUT: 0.7
  EVALUATOR:
    PREDICT_TYPE: phq-subscores
    INPUT_FEATURE_DIM: 768
    CLASSES_RESOLUTION: 32
    N_CLASSES: 4
    N_SUBSCORES: 8
    DROPOUT: 0.5
    STD: 5
    ATTENTION:
      INPUT_DIM: 1
      HIDDEN_DIM: 4
      BASE_WIDTH: 256
      FUSE_TYPE: iAFF
  CRITERION:
    USE_SOFT_LABEL: true
    USE_WEIGHTS: true
  OPTIMIZER:
    LR: 0.0005
    WEIGHT_DECAY: 5e-05
    USE_SAM: true
  SCHEDULER:
    STEP_SIZE: 10
    GAMMA: 0.9
